name: AllInOne
version: '${project.version}'
main: one.muisnowdevs.minecraft.allinone.AllInOne
api-version: 1.20
database: true

commands:
  loc:
    description: 建立與查看玩家們所建立的座標點位
    usage: /<command> [create|remove|list|search]

  unloc:
    description: Disable AllInOne plugin
    usage: /<command>

  "allinone:callback":
    description: Callback function
    usage: /<command> <UUID>